### ISSUE TITLE
Use file object as property in expression definition

### ISSUE THREAD

**Issue by emi80** [ga4gh-rnaseq/schema#11]
As commented in #10, it would be useful to include a `format` property into the expression object.  I think we might use the `file ` object as a property of  the `expression` object to achieve this and have a better representation of the returned object. The definition would look like:
```
expression:
    type: "object"
    description: "Matrix of expression values."
    properties:
      expressionData:
        $ref: "#/definitions/file"
    externalDocs:
      description: "Find out more"
      url: "https://github.com/ga4gh-rnaseq/schema"
    xml:
      name: "expression"
```

**Comment by saupchurch** [comment]
This makes sense to me.  If we are going with a model where the expression objects are created either at data ingest or in response to a filtering query then their representation is virtually the same as a file.

**Comment by emi80** [comment]
I think this is the model we want to use for now.

If we need to add support for streaming data in the future, we might leave the `expression` object as it is now and possibly add an `expressionStream` object for modelling expression streams.

**Comment by saupchurch** [comment]
As an additional clarification...  While the expression object is pretty much the same as a file object and should probably be made redundant, the `http://server_url/expression` endpoint is distinctly different from the `/file` endpoint.

**Comment by emi80** [comment]
Just to finalize this, should we directly use file objects as return values for expression queries and get rid of the `expression` object for now?

**Comment by saupchurch** [comment]
Yes.  The semantics of an expression value file is contained in the HTTPS endpoint.  The delivered object itself is at this point the same as a 'file'.

**Comment by emi80** [comment]
Close via #16
