### ISSUE TITLE
Tags query parameter definition

### ISSUE THREAD

**Issue by emi80** [ga4gh-rnaseq/schema#12]
The `tags` query parameter of various `search` routes is not working for a comma separated list of tags e.g. `https://ga4gh.org/rna/projects/search?tags=bulk,cancer`. This is due to the parameter definition attribute `collectionFormat: multi` which expects multiple parameter instances rather than multiple values e.g. `https://ga4gh.org/rna/projects/search?tags=bulk&tags=cancer`. See [here](https://swagger.io/docs/specification/2-0/describing-parameters/#query-parameters) for more information.

We might either use  `collectionFormat: csv` (which is the default) or use the current specification to implement #2, e.g. `https://ga4gh.org/rna/projects/search?tags=bulk,cancer&tags=single-cell`, with custom logic to parse the comma separated list value.

**Comment by saupchurch** [comment]
I think the behavior that we want to have here is to use `collectionFormat: csv` and parse the list on the backend.  This should reduce some of the long-URL pressure we might run into with more complex querying.
