### ISSUE TITLE
Security review points to be addressed

### ISSUE THREAD

**Issue by rishidev** [ga4gh-rnaseq/schema#18]
Comments from the Data Security Review:

I’ve looked over the Security Questionnaire and inserted some comments and suggestions.  I’ve also reviewed the API specification (https://github.com/ga4gh-rnaseq/schema/blob/master/rnaseq.md).  As I’ve indicated in my comments to the Security Questionnaire, I would like to see this specification recommend the use of the GA4GH AAI standard (to be submitted for approval) for authenticating and authorizing the user.  I think monitoring activity and detecting/responding to potential breaches (mentioned in the Security Questionnaire) are beyond the scope of this specification.  

I think the principal security risks here are denial of service attacks through overly broad requests, and the disclosure of confidential information through URLs.  

Specifically, the Protocol Essentials section of the spec states that “All API invocations are made to a configurable HTTP(S) endpoint.”  I recommend that this specification require that all API invocations be made over TLS, which will authenticate the identity of the server, and protect URLs, which may serve as a kind of covert channel by exposing sensitive information through project IDs, study IDs, tags, etc.  

Also, both Project GET and Study GET specify the ‘id’ parameter as optional:  “If left blank, all available [projects/studies] will be returned.”  It seems unlikely that a user would request all projects or studies without first doing a Search.  Allowing a user to request everything (all projects or all studies) may create an availability risk, which could create a denial of service.  I suggest the team consider making ‘id’ a required parameter and forbidding /*/* for both Project GET and Study GET.

**Comment by emi80** [comment]
API schema has already been updated to only use an HTTPS endpoint in #15

**Comment by emi80** [comment]
I just opened #19 and #20 following this

**Comment by emi80** [comment]
Should we close this?

**Comment by saupchurch** [comment]
I think we have addressed these concerns.  Let's close this and open a new issue if there is anything further from the next round of the security review.
