### ISSUE TITLE
Require 'id' parameter and forbid '//' for Project and Study GET endpoints

### ISSUE THREAD

**Issue by emi80** [ga4gh-rnaseq/schema#19]
Following the comment below from #18:

> Allowing a user to request everything (all projects or all studies) may create an availability risk, which could create a denial of service.

**Comment by emi80** [comment]
`id` parameter is already required for both Project and Study GET endpoints See [this line](https://github.com/ga4gh-rnaseq/schema/blob/master/rnaseq.yaml#L55) and [this line](https://github.com/ga4gh-rnaseq/schema/blob/master/rnaseq.yaml#L131) in the spec file.

This should also forbid the use of `/`.

**Comment by saupchurch** [comment]
This is another disconnect between the yams example and the md specification.  The specification is the md document which still has this set as optional.
