### ISSUE TITLE
OR queries

### ISSUE THREAD

**Issue by emi80** [ga4gh-rnaseq/schema#2]
In the current API specification, all query filters supporting arrays of values represent `AND` queries. For examples, `minExpression` in the [Expression Search Methods](../blob/2c70842/rnaseq.md#expression-search-methods) accepts a `_threshold_ array` object type.  

In order to support OR queries we could allow multiple occurrences of query filters, e.g. `ga4gh.org/rna/expressions/search?minExpression=...&minExpression=...`. Though, the `&` in the query string looks a bit counter-intuitive in this case.

Suggestions and comments are welcome...

**Comment by emiliorighi** [comment]
@emi80 can I close this issue?

**Comment by emi80** [comment]
Yes, let's close this.
