### ISSUE TITLE
Minimal metadata definitions

### ISSUE THREAD

**Issue by saupchurch** [ga4gh-rnaseq/schema#3]
The RNA-seq schema does not have very much defined metadata.  While flexible, the usefulness of the expression matrix is greater if downstream clients can make at least some assumptions concerning the presence and naming of at least some minimal metadata.  Merging datasets from multiple providers also becomes much easier with some common metadata conventions.

Efforts like MIABIS ([https://github.com/MIABIS/miabis/wiki](https://github.com/MIABIS/miabis/wiki)) can be a starting point for selecting a set of metadata.  This is a step towards turning the current numeric matrix model into a more fully featured format for quantification results.

**Comment by hewgreen** [comment]
Although this ticket is about **minimum** standards there may be some value in defining a select list of 'recommended' attributes along side this. But it depends on exactly how the API is aiming to guide the community.
