### ISSUE TITLE
REWS feedback for v1.0 

### ISSUE THREAD

**Issue by rishidev** [ga4gh-rnaseq/schema#32]
Given that there is little nontechnical info available for ethics users, I would recommend the attached document be revised and made available along with the final spec.

An ethics toolkit for rnaseq apis:
https://docs.google.com/document/d/1QeiYFkJDE81Bdl88LEYH0R6fQ-BgOQiKz0-dqaZqeWE

**Comment by saupchurch** [comment]
Complete agreement here.

**Comment by saupchurch** [comment]
@rishidev Link to the draft added.  We should also check with Adrian and see if REWS is OK with the current state of the document.
