### ISSUE TITLE
Caltech server implementation issue(s)

### ISSUE THREAD

**Issue by romgrk** [ga4gh-rnaseq/schema#34]
Hey,

I just wanted to note that even though [TESTING.md](https://github.com/ga4gh-rnaseq/schema/blob/master/TESTING.md) says that caltech's implementation is fine, it isn't for at least one field. If you run:
`curl -X GET --header 'Accept: application/json' 'https://felcat.caltech.edu/rnaget/expressions/search/?page=1&per_page=10'`

It returns:
```
[
  {
    "id": "2a7ab5533ef941eaa59edbfe887b58c4",
    "file_type": "loom",
    "URL": "http://woldlab.caltech.edu/~sau/rnaget/E-MTAB-5423-query-results.tpms.loom",
    "studyID": "6cccbbd76b9c4837bd7342dd616d0fec"
  }
]
```
You can see the `file_type` field, where it should be `fileType`.

**Comment by saupchurch** [comment]
Thank you for reviewing this!  We are in the process of writing a brand new testing and compliance suite (https://github.com/ga4gh-rnaseq/rnaget-compliance-suite has the bare bones now) which will hopefully do a better job of catching these inconsistencies.  I have fixed the felcat server and the `expression` return fields should be correct now.

**Comment by romgrk** [comment]
Cool, thanks :)

**Comment by romgrk** [comment]
hey @saupchurch, I have a few questions regarding the API specs, how it will evolve, and how to make a server implementation. Is there a way I could contact you? I can be contacted at romain dot gregoire at mcgill dot ca.
