### ISSUE TITLE
add `continuous` endpoint

### ISSUE THREAD

**Issue by saupchurch** [ga4gh-rnaseq/schema#38]
The `continuous` endpoint needs to be added back.  Per request it will return a matrix of signal values with samples on the rows and coordinate on the columns

**Comment by saupchurch** [comment]
There are 2 ways to add this endpoint to the framework.  We can add it as part of the rnaget specification.  Servers can then implement one or more of `expression` and `continuous` and use the `Not Implemented` error to flag anything not implemented.  We could alternatively make a separate standards doc to handle this datatype.  Thoughts?

**Comment by romgrk** [comment]
As you mentionned, I'm wondering if we're not trying to conflate two different use-cases that maybe should stay separate from each other. I'll discuss it with David on Monday and I'll get back to you.
