### ISSUE TITLE
Add phenopackets and best practices to metadata section

### ISSUE THREAD

**Issue by saupchurch** [ga4gh-rnaseq/schema#63]
The expression metadata section https://github.com/ga4gh-rnaseq/schema/blob/master/rnaget.md#expression-metadata needs to be expanded to reference the proposed phenopackets standard as well as recommend curie notation #57 and other metadata best practices

**Comment by mellybelly** [comment]
Here is a description of how to implement a term/id combo for ontology terms:
https://schemablocks.org/standards/identifiers-curies.html

you need to reference an ontology class object: https://schemablocks.org/schemas/ga4gh/OntologyClass.html
simply, an id and a label, for example:
{
   "id" : "DUO:0000004",
   "label" : "no restriction"
}

For the metadata schema, this should be changed for the following fields:

Cell line =>
Cell line ID
Cell line label 
(use CLO for now)

phenotype => 
phenotype ID
phenotype label 
(I recommend HPO, NCIT, or ICD )

Cell type =>
Cell type ID
Cell type Label
(I recommend CL, as you have)

organism =>
Organism ID
Organism label
(I recommend NCBI taxon)

sex	=>
Sex ID
Sex Label 
(i recommend PATO as you have)

Tissue =>
Tissue ID
Tissue Label
(I recommend Uberon for anatomical structures, GO for subcellular structures but probably not relevant here)

You may wish to point people at OLS for browsing terms but they do resolve to Ontobee.
Don't worry too much about referencing a fully fledged phenopacket here in your first release. We should discuss and come up with a good strategy.
