### ISSUE TITLE
SwaggerUI and automated documentation generation

### ISSUE THREAD

**Issue by jb-adams** [ga4gh-rnaseq/schema#68]
Currently, the [human-readable specification document](https://github.com/ga4gh-rnaseq/schema/blob/master/rnaget.md) is being written manually. This process should be automated, in which as much documentation as possible is generated from the RNAget OpenAPI yaml file using autodoc tools.

I can work on this. I plan to use the [DRS Spec](https://ga4gh.github.io/data-repository-service-schemas/preview/release/drs-0.1.0/docs/) as a starting point/template. Perhaps the OpenAPI autodoc can be used on a pan-GA4GH scale.

In addition, we should have a Swagger UI for RNAget.

Both the Swagger UI and documentation can be hosted on Github Pages, and can potentially be rebuilt on a CI build schedule.

**Comment by emi80** [comment]
Another nice to consider for API documentation from OpenAPI is [ReDoc](https://github.com/Redocly/redoc). There is a small introduction to it in the [Swagger blog](https://swagger.io/blog/api-development/redoc-openapi-powered-documentation/).

**Comment by jb-adams** [comment]
Thanks @emi80! I like this a lot, I'll likely replace the current Swagger UI with ReDoc.

I think having the spec represented as interactive documentation (ie ReDoc) as well as auto-generated static HTML should be sufficient. I might bundle this "docs build tooling" into a small app, that can be used with other GA4GH standards.

**Comment by emi80** [comment]
Hi @jb-adams, you are welcome. 

It sounds like a good plan. Let me know if I can help somehow.
