### ISSUE TITLE
Minor updates to OpenAPI Spec

### ISSUE THREAD

**Issue by jb-adams** [ga4gh-rnaseq/schema#70]
@saupchurch @emi80 , I've generated a new human-readable spec document from the recent PR. Here's the [link](https://ga4gh-rnaseq.github.io/schema/releases/1.0.0/). There's a couple missing fields in some of the tables, which I think can be fixed by some minor corrections.

1. The [error](https://ga4gh-rnaseq.github.io/schema/releases/1.0.0/#_definitions_error) schema currently doesn't have any description for its `message` property. Can we add a description?
2. the error [responses](https://ga4gh-rnaseq.github.io/schema/releases/1.0.0/#_paths_continuous_returns_filters_for_continuous_searches_responses) for the `/continuous/filters` endpoint don't have any `schema` associated with them. Can we add references to the `error` model, as we have for all other API routes?

Lastly, I should mention that my autodocs app can generate HTML from documents outside the actual API spec. An example of this in the documentation is [Section 5](https://ga4gh-rnaseq.github.io/schema/releases/1.0.0/#_background). I did this so that we could potentially include external information, images, etc in the final webpage.

Should I remove the current Section 5 from the docs? Also, are there any other sections we could/should include in the final webpage?

**Comment by saupchurch** [comment]
I think it's OK to leave Section 5 there for now so we have a consolidated HTML doc.

**Comment by saupchurch** [comment]
closed by #71
