### ISSUE TITLE
/service-info endpoint

### ISSUE THREAD

**Issue by saupchurch** [ga4gh-rnaseq/schema#8]
For future compatibility with the GA4GH Discovery process we need to implement a /service-info endpoint.

**Comment by rishidev** [comment]
From the [service-info YAML](https://github.com/ga4gh-discovery/service-info/blob/develop/service-info.yaml) file it looks like we want name, description, version as a starting point.

**Comment by rishidev** [comment]
This is to be delayed until the service-info has actually been approved by GA4GH

**Comment by rishidev** [comment]
[Service Info](https://github.com/ga4gh-discovery/ga4gh-service-info) has now been approved by GA4GH, so can now be incorporated into the specification.

**Comment by rishidev** [comment]
Update from Miro: 

FYI the specifications have just been released on GitHub, please refer to the tags when using them:
https://github.com/ga4gh-discovery/ga4gh-service-info/releases/tag/v1.0.0
https://github.com/ga4gh-discovery/ga4gh-service-registry/releases/tag/1.0.0

**Comment by saupchurch** [comment]
/service-info endpoint merged into develop and will be part of v1.1 upon release
