### ISSUE TITLE
expression units returned

### ISSUE THREAD

**Issue by hitz** [ga4gh-rnaseq/schema#93]
Should implementation return either or both TPM or FPKM units.  Or other units?
What is the syntax for asking for different units?

Is TPM the default?

**Comment by saupchurch** [comment]
The specification does not currently have a way for a request to specify the units.  The design idea behind this is that RNAget is a retrieval specification and selecting which units to have in the matrix is done when the matrix is defined as part of discovery.

The ticket model has a required field where the units are reported to the client but this is just a report.  Similarly, the selection of default units is left to the discovery implementation.

If you think units should be selectable at the retrieval point we can add it to the specification in a way similar to how the download format is requested.  What do you think?

**Comment by hitz** [comment]
The part that is awkward for us is that RSEM gives us both TPM and FPKM.  So we would presume to store both "matrices" (really 2 vectors for each gene, or whatever) ... but I don't see how "discovery" would apply unless we could distinguish upon query?  I might be missing something obvious.

**Comment by saupchurch** [comment]
closed by #97
